name: Terraform Build

on:
  push:
    branches:
      # Build on main too.
      # This helps with cache performance:
      #   https://github.com/actions/cache/blob/main/tips-and-workarounds.md#use-cache-across-feature-branches
      - main
  workflow_dispatch:  # Allows to trigger workflow manually
  pull_request:

jobs:
  terraform_check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Check for changed files
      uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46.0.5
      id: changed-files
      with:
        files: |
          *.tf

    - name: Install mise
      uses: jdx/mise-action@13abe502c30c1559a5c37dff303831bab82c9402 # 2.2.3
      if: steps.changed-files.outputs.any_changed == 'true'

    - name: Check Terraform Formatting and Docs
      run: ./scripts/terraform_format_and_docs.sh
      if: steps.changed-files.outputs.any_changed == 'true'
